### ISSUE TITLE
Insertar,Actualizar,Eliminar y Buscar

### ISSUE THREAD

**Issue by Ariadnamonserrat10** [SistemasTecTlaxiaco/actividad-11-practica-de-visualizacion-de-datos-equipo-buscadores-de-datos#1]
* Roldan Uriel Arcadio Avila
* Pedro Garcia Garcia
* Ariadna Monserrat López Aparicio

[Insertar,Actualizar,Eliminar y Buscar.pdf](https://github.com/SistemasTecTlaxiaco/actividad-11-practica-de-visualizacion-de-datos-equipo-buscadores-de-datos/files/15488197/Insertar.Actualizar.Eliminar.y.Buscar.pdf)

**Comment by josealfredo79** [comment]
BIen hecho y revisado..
